name: Deploy on Push

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Make HTTP request to deployment script
        run: curl -X GET https://scr-prep.indiaesg.org/list-files